# Generated by Django 4.0.8 on 2022-11-29 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=5)),
                ('endTime', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80, validators=[django.core.validators.EmailValidator])),
                ('company', models.CharField(max_length=80)),
                ('scheduledDate', models.CharField(max_length=10)),
                ('scheduleTime', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('donationAmount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, null=True)),
                ('minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedulerGetResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('isSuccess', models.BooleanField()),
                ('message', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
