# Generated by Django 4.0.8 on 2022-11-30 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=80, validators=[django.core.validators.EmailValidator, django.core.validators.EmailValidator()]),
        ),
    ]
