# Generated by Django 4.0.8 on 2022-12-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='isTestOnly',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
